apiVersion: dapr/v1alpha1
kind: Component
metadata: 
  name: reservations
spec: 
  type: pubsub.redis
  matadata: 
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""